CREATE SCHEMA my-test-db-name;
use my-test-db-name;

CREATE TABLE EMP_PERSONAL (
EMP_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMP_NAME VARCHAR(50) NOT NULL,
EMP_DOJ   DATE NOT NULL,
EMP_CONTACT VARCHAR(20) NULL,
EMP_EMAIL VARCHAR(20) NULL,
EMP_DOB DATE NOT NULL
);

INSERT INTO EMP_PERSONAL(EMP_NAME, EMP_DOJ, EMP_CONTACT, EMP_EMAIL, EMP_DOB)
VALUES ('Vinny', '2020-01-01', '989898989898', 'vinny@vinni.com', '1996-01-01');

CREATE TABLE EMP_DOCUMENT(
DOC_ID INTEGER NOT NULL AUTO_INCREMENT,
EMP_ID INTEGER NOT NULL,
DOC_TYPE  VARCHAR(15) NOT NULL,
DOC_NUMBER VARCHAR(20) NOT NULL ,
EXPIRY_DATE DATE NOT NULL ,
PRIMARY KEY(DOC_ID),
FOREIGN KEY(EMP_ID) REFERENCES EMP_PERSONAL (EMP_ID)
);

INSERT INTO EMP_DOCUMENT(EMP_ID, DOC_TYPE, DOC_NUMBER, EXPIRY_DATE)
VALUES (1, 'CSV', '6789', '2020-08-09');

CREATE TABLE EMP_ADDRESS(
ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
EMP_ID INTEGER NOT NULL,
ADDRESS VARCHAR(60) NULL,
ADDRESS_TYPE VARCHAR(15) NULL,
ZIP_CODE VARCHAR(10) NULL,
PRIMARY KEY (ADDRESS_ID),
FOREIGN KEY (EMP_ID) REFERENCES EMP_PERSONAL (EMP_ID)
);

INSERT INTO EMP_ADDRESS(EMP_ID, ADDRESS, ADDRESS_TYPE, ZIP_CODE)
VALUES (1, 'Fairborn', 'home', '45324');

CREATE  TABLE EMP_EDUCATION(
EDUCATION_ID INTEGER NOT NULL AUTO_INCREMENT ,
EMP_ID INTEGER NOT NULL,
EDUCATION_NAME VARCHAR(50) NOT NULL,
INSTITUTE_NAME VARCHAR(100) NULL,
PERCENTAGE DOUBLE NOT NULL,
PASSING_YEAR INTEGER NOT NULL,
TYPE VARCHAR(20) NOT NULL,
PRIMARY KEY (EDUCATION_ID),
FOREIGN KEY (EMP_ID) REFERENCES EMP_PERSONAL(EMP_ID)
);

INSERT INTO EMP_EDUCATION(EMP_ID, EDUCATION_NAME,INSTITUTE_NAME, PERCENTAGE,PASSING_YEAR,`TYPE`)
VALUES (1, 'PG', 'CVSR','78.0', '2018','CS');

CREATE TABLE PROJECT(
PROJECT_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
PROJECT_NAME VARCHAR(100) NOT NULL,
TECHNOLOGIES VARCHAR(100) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
REMARKS VARCHAR(30) NULL,
PROJECT_STATUS VARCHAR(20) NOT NULL
);

INSERT INTO PROJECT(PROJECT_NAME, TECHNOLOGIES, START_DATE,END_DATE, REMARKS,PROJECT_STATUS)
VALUES ('HRMS', 'JAVA', '2020-07-23','2020-08-23', 'to be completed ','implementation');

CREATE TABLE EMP_PROJECT_ALLOCATION(
ALLOCATION_ID INTEGER NOT NULL AUTO_INCREMENT,
PROJECT_ID INTEGER NOT NULL,
EMP_ID INTEGER NOT NULL,
ALLOCATION_STATUS VARCHAR(20) NOT NULL,
PRIMARY KEY (ALLOCATION_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
FOREIGN KEY (EMP_ID) REFERENCES EMP_PERSONAL
(EMP_ID)
);

INSERT INTO EMP_PROJECT_ALLOCATION(PROJECT_ID, EMP_ID, ALLOCATION_STATUS)
VALUES ('1', '1', 'alloted');


CREATE TABLE PROJECT_EMP_PROJECT_ALLOCATION(
PROJECT_ID INTEGER ,
ALLOCATION_ID INTEGER );













